sudo: required
language: java
jdk:
- oraclejdk8

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: morning-refuge-4717
  on:
    repo: BrianKolowitz/testassignment4-BrianKolowitz
